### ISSUE TITLE
Routine feature request: shrink png images

### ISSUE THREAD

**Issue by gadenbuie** [rstudio/shiny-workflows#14]
It'd be helpful to add an action that

* Installs `optipng`
* Runs `optipng` on a list of directories provided to the action
* Commits any updates to those files back to the repo

The actual code might look something like this:

```bash
# Shrink images in man/figures
sudo apt-get install optipng
optipng man/figures/*.png
git commit man/figures/*.png -m "Shrink images in man/figures (Github Action)" || echo "No changes to man/figures/*.png"
```

but it'd be extra helpful to allow an array input of directories.

```yaml
- name: Shrink pngs
  uses: rstudio/shinycoreci/shrink-png@v1
  with:
    paths:
      - man/figures/*.png
      - vignettes/**.png
```
